[package]
name = "sdm_browser"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
dioxus = { version = "0.5.0-alpha.0", features = ["desktop"] }
reqwest = { version = "0.11.26", features = ["json"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_yaml = "0.9.33"
