[application]
name = "sdm_browser"
default_platform = "desktop"
out_dir = "dist"
asset_dir = "public"

[web.watcher]
reload_html = true
watch_path = ["src", "public"]

[web.resource]
style = ["/tailwind.css"]
script = []

[web.resource.dev]
style = []
script = []